#!/usr/bin/env python3
"""Builds src/emoji_alias.c: Discord's own emoji names that src/emoji_data.c lacks.

src/emoji_data.c holds the picker, with gemoji's names. Discord accepts more
names when typing ":name:" (":slight_smile:", ":flag_us:", ":regional_indicator_a:"
...); they come from the discord-emoji package (MIT License, Copyright (c) 2020
Samuel Voeller, 2016-2020 Marek Kulik), pinned below. Skin tone variants are
left out: emoji.c adds the modifier itself (":thumbsup_tone2:", ":skin-tone-2:").

Usage, from the repository root:  python tools/make_emoji_aliases.py [package.tgz]
"""
import hashlib
import io
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

VERSION = "2.5.3"
URL = f"https://registry.npmjs.org/discord-emoji/-/discord-emoji-{VERSION}.tgz"
SHA1 = "de9d2aa8da700fe42952adefcfb406f56c050152"
ROOT = Path(__file__).resolve().parent.parent
TONE = re.compile(r"_(tone[1-5]|light_skin_tone|medium_light_skin_tone|medium_skin_tone|medium_dark_skin_tone|dark_skin_tone)$")
NAME = re.compile(r"^[a-z0-9_+-]+$")
MODIFIERS = ["\U0001F3FB", "\U0001F3FC", "\U0001F3FD", "\U0001F3FE", "\U0001F3FF"]


def package(argv):
    data = Path(argv[1]).read_bytes() if len(argv) > 1 else urllib.request.urlopen(URL, timeout=60).read()
    if hashlib.sha1(data).hexdigest() != SHA1:
        sys.exit(f"make_emoji_aliases: {URL} does not match its pinned checksum")
    with tarfile.open(fileobj=io.BytesIO(data)) as tar:
        return tar.extractfile("package/script/mod.js").read().decode("utf-8")


def c_string(s):
    return "".join(f"\\x{b:02X}" for b in s.encode("utf-8"))


def main():
    table = dict(re.findall(r'^\s*"([^"]+)": "([^"]+)",?$', package(sys.argv), re.M))
    ours = set()
    for names in re.findall(r'\{"(?:[^"\\]|\\.)*", "([^"]*)"\}', (ROOT / "src" / "emoji_data.c").read_text(encoding="utf-8")):
        ours.update(names.split())
    aliases = {n: e for n, e in table.items() if n not in ours and NAME.match(n) and not TONE.search(n)}
    for i, m in enumerate(MODIFIERS):
        aliases[f"skin-tone-{i + 1}"] = m
    lines = [
        "/*",
        " * Discord's emoji names missing from emoji_data.c, sorted: \"name\\0emoji\\0\" each.",
        f" * Generated by tools/make_emoji_aliases.py from discord-emoji {VERSION}",
        " * (https://github.com/xCykrix/discord_emoji), MIT License,",
        " * Copyright (c) 2020 Samuel Voeller, Copyright (c) 2016-2020 Marek Kulik.",
        " */",
        '#include "emoji.h"',
        "",
        "const char k_emoji_aliases[] =",
    ]
    for name in sorted(aliases):
        lines.append(f'    "{name}\\0{c_string(aliases[name])}\\0"')
    lines[-1] += ";"
    lines += [f"const int k_nemoji_aliases = {len(aliases)};", ""]
    out = ROOT / "src" / "emoji_alias.c"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{out.relative_to(ROOT)}: {len(aliases)} names")


if __name__ == "__main__":
    main()
