#pragma once

/* Numeric tables of the SILK decoder (RFC 6716). */

extern const unsigned char k_LTP_per_index_iCDF[3];
extern const unsigned char k_LTP_gain_iCDF_0[8];
extern const unsigned char k_LTP_gain_iCDF_1[16];
extern const unsigned char k_LTP_gain_iCDF_2[32];
extern const signed char k_LTP_gain_vq_0[8][5];
extern const signed char k_LTP_gain_vq_1[16][5];
extern const signed char k_LTP_gain_vq_2[32][5];
extern const unsigned char k_NLSF_CB1_NB_MB_Q8[320];
extern const unsigned char k_NLSF_CB1_iCDF_NB_MB[64];
extern const unsigned char k_NLSF_CB2_SELECT_NB_MB[160];
extern const unsigned char k_NLSF_CB2_iCDF_NB_MB[72];
extern const unsigned char k_NLSF_PRED_NB_MB_Q8[18];
extern const short k_NLSF_DELTA_MIN_NB_MB_Q15[11];
extern const unsigned char k_NLSF_CB1_WB_Q8[512];
extern const unsigned char k_NLSF_CB1_iCDF_WB[64];
extern const unsigned char k_NLSF_CB2_SELECT_WB[256];
extern const unsigned char k_NLSF_CB2_iCDF_WB[72];
extern const unsigned char k_NLSF_PRED_WB_Q8[30];
extern const short k_NLSF_DELTA_MIN_WB_Q15[17];
extern const unsigned char k_gain_iCDF[3][8];
extern const unsigned char k_delta_gain_iCDF[41];
extern const short k_stereo_pred_quant_Q13[16];
extern const unsigned char k_stereo_pred_joint_iCDF[25];
extern const unsigned char k_stereo_only_code_mid_iCDF[2];
extern const unsigned char k_LBRR_flags_2_iCDF[3];
extern const unsigned char k_LBRR_flags_3_iCDF[7];
extern const unsigned char k_lsb_iCDF[2];
extern const unsigned char k_LTPscale_iCDF[3];
extern const unsigned char k_type_offset_VAD_iCDF[4];
extern const unsigned char k_type_offset_no_VAD_iCDF[2];
extern const unsigned char k_NLSF_interpolation_factor_iCDF[5];
extern const short k_Quantization_Offsets_Q10[2][2];
extern const short k_LTPScales_table_Q14[3];
extern const unsigned char k_uniform3_iCDF[3];
extern const unsigned char k_uniform4_iCDF[4];
extern const unsigned char k_uniform5_iCDF[5];
extern const unsigned char k_uniform6_iCDF[6];
extern const unsigned char k_uniform8_iCDF[8];
extern const unsigned char k_NLSF_EXT_iCDF[7];
extern const unsigned char k_pitch_lag_iCDF[32];
extern const unsigned char k_pitch_delta_iCDF[21];
extern const unsigned char k_pitch_contour_iCDF[34];
extern const unsigned char k_pitch_contour_NB_iCDF[11];
extern const unsigned char k_pitch_contour_10_ms_iCDF[12];
extern const unsigned char k_pitch_contour_10_ms_NB_iCDF[3];
extern const unsigned char k_pulses_per_block_iCDF[10][18];
extern const unsigned char k_rate_levels_iCDF[2][9];
extern const unsigned char k_shell_code_table0[152];
extern const unsigned char k_shell_code_table1[152];
extern const unsigned char k_shell_code_table2[152];
extern const unsigned char k_shell_code_table3[152];
extern const unsigned char k_shell_code_table_offsets[17];
extern const unsigned char k_sign_iCDF[42];
extern const signed char k_CB_lags_stage2_10_ms[2][3];
extern const signed char k_CB_lags_stage3_10_ms[2][12];
extern const signed char k_CB_lags_stage2[4][11];
extern const signed char k_CB_lags_stage3[4][34];
extern const short k_LSFCosTab_FIX_Q12[129];
extern const short k_resampler_frac_FIR_12[12][4];
